### ISSUE TITLE
Upgrading versions

### ISSUE THREAD

**Issue by slickspidey** [stuartridout/teamlink#17]
Could I get instructions on how to upgrade to the most recent release? Only asking because I tried upgrading today (to 1.0.0.23) and Power Apps says it's already installed but it is still showing as the older version (1.0.0.19).

Here's what I did:
1. Downloaded the most recent release
2. Imported solution to the same Team's channel
3. It said this version of the solution is an upgrade to 1.0.0.19, then I hit Next
4. It imported successfully
5. Still shows as version 1.0.0.19 but shows my history 

![image](https://user-images.githubusercontent.com/25755070/170120577-8ded55bc-2731-4515-bfcd-a1a85db063da.png)

Could you help me figure out how to make the most recent version active and published to the Team's channel I already have it in without having to remove it?

**Comment by stuartridout** [comment]
Hi.  It may be because there is an unmanaged layer.  This is where a change/customisation has happened to the app which is preventing the update from being applied.  

Go to https://flow.Microsoft.com and choose the environment from the drop down in the top right corner.  Under the solutions you should be able to find the TeamLink solution.  

The instructions for removing the unmanaged layer is at https://docs.microsoft.com/en-us/power-apps/maker/data-platform/solution-layers

**Comment by BA279** [comment]
Hi,
I´m also struggling with the update. I can´t see the "See solution layers" button to delete the unmanaged layer. Please see the screenshot.

![image](https://user-images.githubusercontent.com/123933359/215423508-1fa3de8f-b785-4b7a-92f8-205862cfa201.png)
Any ideas? Thanks!
