### ISSUE TITLE
Upgrade to .30 fails - Solution "TeamLink" failed to import: Solution Upgrade action failed after import as holding. InnerException is: You cannot delete this form because it is the only fallback form of type main for the cr599_site entity. Each entity must have at least one fallback form for each form type..

### ISSUE THREAD

**Issue by digitalanalogue9** [stuartridout/teamlink#33]
Hi Stuart,
Very cool app - big props for making it!

I tried to upgrade from 1.0.23 to 1.0.30 and received the following message
Solution "TeamLink" failed to import: Solution Upgrade action failed after import as holding. InnerException is: You cannot delete this form because it is the only fallback form of type main for the cr599_site entity. Each entity must have at least one fallback form for each form type.

[TeamLink_import.xlsx](https://github.com/stuartridout/teamlink/files/9339661/TeamLink_import.xlsx)

Any help gratefully received 

Thanks
Dan

**Comment by stuartridout** [comment]
Hi Dan, thanks for the kind words.

This is a headscratcher 🤔 as I've not seen this before.  I've just created a new 1.0.23 version and upgraded successfully to 1.0.30 with no problems.   In fact a quick search online only highlights issues from old CRM instances many years ago.

So here are a few questions

1. Have you tried multiple times in case there was a weird glitch the first time?
2. Have you checked for (and removed) unmanaged layers? As this is a Dataverse for Teams solution this needs to be done from the Power Automate Maker portal at https://make.powerautomate.com - See this documentation https://docs.microsoft.com/en-us/power-apps/maker/data-platform/solution-layers 
3. Could you try upgrading the solution from the Power Automate maker portal instead of in Teams - https://make.powerautomate.com 

Still no luck?   Could you provide a little more info about your setup and any changes made.   Is it in Dataverse for Teams or Full Dataverse etc.

**Comment by digitalanalogue9** [comment]
We did try multiple times but no cigar - and I thought (you can tell I'm an amateur in dynamics!) I'd removed the unmanaged layer where we'd had to customise some bits.  However, happy to say we (well the person in the my team who knows what they are doing ) solved it by creating some fallback forms in the default solution and then running the update again and all sorted.  

We are running it in Dataverse rather than Dataverse for Teams - started in our dev team but think it's a good shout for the whole org especially as folks work across departments in project teams.  

When I showed it to a few people, a number of ideas came flooding out like talking to Exchange online or setting your teams message stuff e.g "This week, I am planning to be in the office Mon, Tues and remote otherwise" and allowing the user to set if their office could be used for meetings if they were working remotely and lastly (I think another issue has mentioned this, augmenting the options might be useful but am aiming for less is more approach. 

We also thought about if you could double up the app for a rough busyness e.g. Do not disturb, Busy, Available , Not at work.  That could be another app as I think TeamLink does one thing, does it well and it might make it too busy
