### ISSUE TITLE
User stuck on First Time Admin Setup screen ... even though they are not an admin!

### ISSUE THREAD

**Issue by digitalanalogue9** [stuartridout/teamlink#52]
One of the folks in my team had previously been able to access the power app but when they open it now they see
![image](https://user-images.githubusercontent.com/1837710/215889547-856f32cd-9760-4ca2-ad1d-8a25d4f1bc38.png)

I think they've got through the initial setup before based on the fact because they're filling in the weekly card sent by Power Automate and I think that only kicks off if you've set your status at least once/gone through the user set up ?  Have checked Notification Records and can find them - bypass disclaimer = true and same with To Be Notified

They are not an admin and other people in the MS Team can see TeamLink with no issue.

**Comment by stuartridout** [comment]
This would normally indicate that they don't have access to the data. This would usually be because they're not a member of the Team or they've been removed from the group that the data is shared with.  

From the screenshot it looks like they're accessing the app via the Team, is that the case?  I would assume they're still a member of the team in that case. 

Can you confirm?

**Comment by digitalanalogue9** [comment]
I'd love to say yes rn but will need my team to give me a hand there !!

They are accessing the app via the team.   However, rather than installing in Teams DataVerse, we've installed TeamLink in a DataVerse environment.  TeamLink is a feature of a number of MS Teams teams so intent was to save them effort updating in multiple places.  

It's not affected anyone else - the only they noticed was somehow their UPN was misspelt compared to their email - getting that rectified but didn't think that would impact.  

And thank you for super swift reply!

**Comment by stuartridout** [comment]
Ok. Installing in standard Dataverse is perfect.  There is nothing wrong with that.  

They've received this message because they have access to the app but not the data.  

You may need to get whoever is the environment admin to investigate why they no longer have access to the tables.  If there's a change in their UPN it may not have flowed through into their Dataverse user record permissions.  

This appears to be a Dataverse problem rather than a TeamLink specific problem.

**Comment by digitalanalogue9** [comment]
Closing - they had been removed from the security group for the dataverse environment.
