### ISSUE TITLE
Upgrade to 2.0.0.3 challenges but might be due to installation to standard Dataverse environment!

### ISSUE THREAD

**Issue by digitalanalogue9** [stuartridout/teamlink#53]
TeamLink installed in standard Dataverse Environment.  Intent is the same TeamLink whatever MS Team the PowerApp is added to.

- cloned our TeamLink environment
- removed the unmanaged layer (version had some tweaks to a flow and to some of the wording in the app
- imported 2.0.0.3 solution - some warnings about some localisations that weren't available 

Initial observations on load
It did present me with a button about localisations which I pressed but no options to choose a language

And then the UI shows an interesting mix of Spanish and English
![image](https://user-images.githubusercontent.com/1837710/215903100-18f37b1a-f49a-4e8f-aa72-2d5ed723ae8a.png)

Is this because I didn't install TeamLink to a Teams Environment?  Noted in the YouTube video, TeamLink could be pinned to the Teams Apps and that you could set some defaults like language there.  I'm guessing this then sets the locale param in the query string when it loads the app.  And assuming because of not installing it in Teams Dataverse, I might not get the ability to pin the app :(

from initialLoading.triggerLoading.OnTimerStart
Set(
    userLocale,
    Param("locale")
);

... so maybe a local tweak in the app and replicate how you query TeamLinkSettings by create a custom SettingName.  The standard dataverse install would mean a global langugage setting but could maybe add that as a user setting ?

Also post upgrade, 

- it duplicated the options in the Present Option table (I don't remember seeing the add custom images bit in the admin actions screen but may have been clicking in haste!)

- it didn't populate the TeamLinkSettings with the extra bits (noted from video that you typed them in so that might be intentional?)
Just in case anyone comes across this they were.. 

AppName		string
bgColour	 		hex
bgGrey		        hex
headerColour		hex
primaryButton  	hex
primaryButtonText 	hex
lightText 			hex
secondaryText		hex
tertiaryText		hex
primaryForeground	hex
MeetIcon			svg
ShowProfilePics	boolean

I only had
PurgeAgeDays	int    7
ShowProfilePics	boolean

**Comment by stuartridout** [comment]
Firstly, installing in full Dataverse is the perfect use case.  We only highlight Dataverse for Teams as many of the users don't have full Dataverse.  The intention is perfect, one TeamLink across all Teams. 

The language prompt is intentional and is an admin setting.  Rather than selecting your personal language it is a system load of the language strings as they are not present in an upgrade.  Users shouldn't see this.  

The TeamLink upgrade was tested in a full Dataverse environment so not sure why you've got multiple present options.  I am wondering if it is connected to the other issue you have raised (with initial setup) as that is where the Present Options are initially created. Alternatively it could have happened during the environment cloning. 

I'm interested in why you have Spanish as it would default to English in the absence of a language Param obtained from Teams.  Are you accessing this in browser? 

The extra TeamLink settings are manually created.  I'm going to add extra documentation about how to configure them as there are extras you've not got listed like the actual logo for the app.  

Lastly, you mentioned not being able to pin the app because of not being installed in Dataverse for Teams.  Do you mean on the left hand app bar?  Could you expand on that please.

**Comment by digitalanalogue9** [comment]
Cool - we're within what was in your head when making!

I'll ditch the environment and start again.  Will remove the unmanaged layer first.  And initial test will be from Teams rather than web.

re Language - I was testing from a web page rather than from Teams so locale param would have been missing so value would be null.  Once I've started again, I'll check the data/code as to why it might have chosen Spanish first.

re the Present Options - Will check there's 4 before upgrading and what happens after the upgrade and first usage.  

And re pinning - yes I meant the left hand app bar - assumption on my part as I hadn't yet added it to teams - I'll revert once I've done that.

**Comment by digitalanalogue9** [comment]
Closing - after removing the customisations and then updating the solution - worked as expected

- Created new environment
- Copied live environment to this environment
- Went into solution and removed all unmanaged layers
   - One from canvas app -> known customisations
   - From flows -> looked like auth info
- Added to test MS Team
![image](https://user-images.githubusercontent.com/1837710/218276763-5a2f4187-012f-40f1-bf6b-e41a2f0e47a2.png)
![image](https://user-images.githubusercontent.com/1837710/218276773-939e473c-a88b-450e-92e9-2486547ca46f.png)
- 
![image](https://user-images.githubusercontent.com/1837710/218276783-b0a1ec5f-4a07-4a4c-9bc2-c7eebe5a8e55.png)
- also tested on web and language was en-US
