### ISSUE TITLE
How does reminder functionality work

### ISSUE THREAD

**Issue by harshdamaniahd** [stuartridout/teamlink#8]
Daily TeamLink Check For End of Week and Send Card
Send TeamLink Reminder Card

can you provide me some insights

**Comment by stuartridout** [comment]
Hi there.  Just updating the documentation at present.  

The reminder card is powered by Power Automate.  Each day the master flow runs and will check each person's nominated work week to see if today is their last working day.  If it is then it calls a second flow which sends them an adaptive card. 

The second child flow checks to see if they already have any presences nominated for the following week and pre-fills the adaptive card in that condition.  Otherwise it presents an empty drop down for them to complete. 

When the user submits the card the child flow will write that into the Dataverse environment.
